services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: vrx-postgres
    environment:
      POSTGRES_DB: vrx_dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password} # Usa variable de entorno, con 'password' como default
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vrx_dashboard"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - vrx-network
    restart: unless-stopped

  # Aplicación principal
  app:
    build: .
    container_name: vrx-dashboard-app
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-password}@postgres:5432/vrx_dashboard
      API_HOST: 0.0.0.0
      API_PORT: 8000
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:8000}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:8000,http://localhost:3000}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - reports_data:/app/vRx-Report/reports
    networks:
      - vrx-network
    restart: unless-stopped

volumes:
  postgres_data:
  reports_data:

networks:
  vrx-network:
    driver: bridge
